cache:
  key: "$CI_BUILD_REF_NAME node:10.10-alpine"
  paths:
    - node_modules/

stages:
  - release
  - deploy

release:
  stage: release
  image: docker:latest
  only:
    - "site"
  services:
    - docker:dind
TstymHcEfs6MwZzY51Av    DOCKER_DRIVER: "overlay"
  before_script:
    - docker version
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - echo ${FOXENV} | base64 -d > ./.env
  script:
    - "docker build -t registry.gitlab.com/rtexel/fox:latest --pull ."
    - "docker push registry.gitlab.com/rtexel/fox:latest"
  after_script:
    - "docker logout registry.gitlab.com/"

deploy:
  stage: deploy
  image: gitlab/dind:latest
  only:
    - "site"
  environment: production
  services:
    - docker:dind
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - scp -r ./.env ./docker-compose.yml root@68.183.20.215:~/
    - ssh root@${DEPLOYMENT_SERVER_IP} "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker-compose -f docker-compose.yml stop; docker-compose -f docker-compose.yml rm nuxt --force; docker pull registry.gitlab.com/rtexel/fox:latest; docker-compose -f docker-compose.yml up -d"
